[package]
name = "runtime_units"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
keywords =  ["units", "measurement", "SI", "dimensional-analysis"]
description = "A run-time Rust library for working with units of measurement and conversions between them."
repository = "https://github.com/mattrjackson/runtime_units_rs"
readme = "README.md"
authors = ["Matt Jackson <mattrjackson@gmail.com>"]

[dependencies]
bitfield-struct = "0.6.0"
once_cell = "1.19.0"
paste = "1.0.14"
serde = {version = "1.0.197", optional = true }
serde_json = { version = "1.0.114", optional = true }
strum = "0.26.1"
strum_macros = "0.26.1"
utoipa = { version = "4.2.0", optional = true , features=["axum_extras", "uuid","chrono", "url", "time", "openapi_extensions"]}

[profile.test]
opt-level = 3
debug = true


[features]
default = ["Length", "Mass", "Angle", "Luminance", "TemperatureInterval", "AmountOfSubstance", "ElectricCurrent"]
serde = ["dep:serde", "dep:serde_json"]
utoipa = ["dep:utoipa"]
All = ["Absement","AbsorbedDose","Acceleration","Action","AmountOfSubstance","Angle","AngularAcceleration","AngularJerk","AngularVelocity","ArealDensityOfStates","ArealMassDensity","ArealNumberDensity","ArealNumberRate","Area","AvailableEnergy","Capacitance","CatalyticActivityConcentration","CatalyticActivity","Curvature","DiffusionCoefficient","DoseEquivalent","DynamicViscosity","ElectricalConductance","ElectricalConductivity","ElectricalMobility","ElectricalResistance","ElectricalResistivity","ElectricChargeArealDensity","ElectricChargeLinearDensity","ElectricCharge","ElectricChargeVolumetricDensity","ElectricCurrentDensity","ElectricCurrent","ElectricDipoleMoment","ElectricDisplacementField","ElectricField","ElectricFlux","ElectricPermittivity","ElectricPotential","ElectricQuadrupoleMoment","Energy","Force","FrequencyDrift","Frequency","HeatCapacity","HeatFluxDensity","HeatTransfer","Inductance","InformationRate","Information","Jerk","Length","LinearDensityOfStates","LinearMassDensity","LinearNumberDensity","LinearNumberRate","LinearPowerDensity","Luminance","LuminousIntensity","MagneticFieldStrength","MagneticFluxDensity","MagneticFlux","MagneticMoment","MagneticPermeability","MassConcentration","MassDensity","MassFlux","MassRate","Mass","Molality","MolarConcentration","MolarEnergy","MolarFlux","MolarHeatCapacity","MolarMass","MolarRadioactivity","MolarVolume","MomentOfInertia","Momentum","Power","PressureImpulse","Pressure","RadiantExposure","Radioactivity","Ratio","ReciprocalLength","SolidAngle","SpecificArea","SpecificHeatCapacity","SpecificRadioactivity","SpecificVolume","SurfaceElectricCurrentDensity","TemperatureCoefficient","TemperatureGradient","TemperatureInterval","ThermalConductivity","ThermodynamicTemperature","Time","Torque","Velocity","VolumeRate","Volume","VolumetricDensityOfStates","VolumetricHeatCapacity","VolumetricNumberDensity","VolumetricNumberRate","VolumetricPowerDensity"]
Absement=[]
AbsorbedDose=[]
Acceleration=[]
Action=["Energy"]
AmountOfSubstance=[]
Angle=[]
AngularAcceleration=[]
AngularJerk=[]
AngularVelocity=[]
ArealDensityOfStates=[]
ArealMassDensity=[]
ArealNumberDensity=[]
ArealNumberRate=[]
Area=[]
AvailableEnergy=[]
Capacitance=[]
CatalyticActivityConcentration=[]
CatalyticActivity=[]
Curvature=[]
DiffusionCoefficient=[]
DoseEquivalent=[]
DynamicViscosity=[]
ElectricalConductance=[]
ElectricalConductivity=[]
ElectricalMobility=[]
ElectricalResistance=[]
ElectricalResistivity=[]
ElectricChargeArealDensity=[]
ElectricChargeLinearDensity=[]
ElectricCharge=[]
ElectricChargeVolumetricDensity=[]
ElectricCurrentDensity=[]
ElectricCurrent=[]
ElectricDipoleMoment=[]
ElectricDisplacementField=[]
ElectricField=[]
ElectricFlux=[]
ElectricPermittivity=[]
ElectricPotential=[]
ElectricQuadrupoleMoment=[]
Energy=[]
Force=[]
FrequencyDrift=[]
Frequency=[]
HeatCapacity=[]
HeatFluxDensity=[]
HeatTransfer=[]
Inductance=[]
InformationRate=[]
Information=[]
Jerk=[]
Length=[]
LinearDensityOfStates=[]
LinearMassDensity=[]
LinearNumberDensity=[]
LinearNumberRate=[]
LinearPowerDensity=[]
Luminance=[]
LuminousIntensity=[]
MagneticFieldStrength=[]
MagneticFluxDensity=[]
MagneticFlux=[]
MagneticMoment=[]
MagneticPermeability=[]
MassConcentration=[]
MassDensity=[]
MassFlux=[]
MassRate=[]
Mass=[]
Molality=[]
MolarConcentration=[]
MolarEnergy=[]
MolarFlux=[]
MolarHeatCapacity=[]
MolarMass=[]
MolarRadioactivity=[]
MolarVolume=[]
MomentOfInertia=[]
Momentum=[]
Power=[]
PressureImpulse=[]
Pressure=[]
RadiantExposure=[]
Radioactivity=[]
Ratio=[]
ReciprocalLength=[]
SolidAngle=[]
SpecificArea=[]
SpecificHeatCapacity=[]
SpecificRadioactivity=[]
SpecificVolume=[]
SurfaceElectricCurrentDensity=[]
TemperatureCoefficient=[]
TemperatureGradient=[]
TemperatureInterval=[]
ThermalConductivity=[]
ThermodynamicTemperature=[]
Time=[]
Torque=[]
Velocity=[]
VolumeRate=[]
Volume=[]
VolumetricDensityOfStates=[]
VolumetricHeatCapacity=[]
VolumetricNumberDensity=[]
VolumetricNumberRate=[]
VolumetricPowerDensity=[]
